title: Snipcart Test
description: Testing snipcart - Guus
url: https://itsguus.github.io/snipcart-test/

permalink: /blog/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: products
    values:
      layout: "product"



collections:
  products:
    output: true
    permalink: /products/:title/
