title: Snipcart Test
description: Testing snipcart - Guus
url: https://adored-bagpipe.cloudvent.net


defaults:
  - scope: 
      path: ""
    values:
      language: en
  - scope: 
      path: "nl"
    values:
      language: nl
  - scope:
      path: "_products/en" 
    values:
      language: en
      layout: product
      permalink: /en/products/:title/
  - scope:
      path: "_products/nl"
      type: products
    values:
      language: nl
      layout: product
      permalink: /nl/producten/:title/

collections: 
  products:
    output: true